### ISSUE TITLE
Standard welcome page contents

### ISSUE THREAD

**Issue by rhcarvalho** [sclorg/rails-ex#20]
I want to determine what will be the content of our welcome pages. Layout stays as v2, rails-ex and dancer-ex.
The current page for rails-ex:
![image](https://cloud.githubusercontent.com/assets/88819/8212473/3ca91cfe-151c-11e5-9ed4-2e77ac188389.png)

Issues:
1. **Web Console** section: I'm unsure the copy "add collaborator access authorizations, designate custom domain aliases, and manage domain memberships" relates to the web console in v3
2. **Command Line Tools** section: documentation is for v2
3. **Development Resources** section: except for StackOverflow and Git docs, all links point to v2 resources.
4. In **Deploying code changes**, the first thing we do is list the steps to use GitHub webhook, but that won't work if you are trying OpenShift on a non-GitHub accessible network, and it not totally required.
5. **Working in your local Git repository** links to v2 documentation
6. **Working in your local Git repository** steps won't work unless you change the template parameter to point to your fork of the github repo.

Content present in django-ex and not in rails-ex:
- Steps how the example project was created
- Dynamic request info: hostname of the pod serving the request, database connection info, page view counter
  ![image](https://cloud.githubusercontent.com/assets/88819/8213216/b88ba1ee-1520-11e5-9af1-dc82acf2d9e1.png)

---

@bparees @mfojtik @jhadvig @ewolinetz could you please comment on the points above?
Once I have a clearer picture of the contents we want in the welcome pages I can make PRs to update what's needed.

**Comment by bparees** [comment]
1) "you can use the web console to view the state of your application components and launch new builds"
2) command line tools should link to our v3 CLI docs.
3) remove links to v2 content, link to v3 docs.
4) add a note that it requires your openshift master be reachable from github.
5) nothing wrong w/ the clone steps, but need to update the doc to say "after pushing changes, you'll need to manually trigger a build if you did not setup the webhook" and remove the reference to v2 and the README
6) we can't explain all this in the welcome page.   it doesn't even belong there since at that point they've already stood the app up using whatever repository they chose.  punt.

can live w/o "how this repo was created"
don't care about the dynamic request info at this point.

**Comment by rhcarvalho** [comment]
1) From my perspective, if you arrived at the welcome page, then you already know what the Web Console is and what you can do with it?!
2) Also, installing the tools is likely already done -- I don't see the point in covering this in the welcome page. How else could you have deployed the example app?

**Comment by bparees** [comment]
1) probably but not necessarily.  you didn't necessarily create the app via the web console.
2) via the web console?

**Comment by rhcarvalho** [comment]
2) do we have a doc page on how to install the CLI tools or just GH readme?

**Comment by bparees** [comment]
@rhcarvalho i don't care about how to install them, just how to use them.
